# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5187c1a28542849a88a047a86cfc45a01e89fcfeaf597a0fa1d0699fc89019cad87428b8682762c7d43d8f19f556b10126ecfd7f1b5528034bc78f074bf94d63

test:
  secret_key_base: ff7b202bafde4444e646bcd28879b777f8fa5c3fd7407bfb39cc48c13f3d437fb2b9f557830d96f014d5e77c445b5a0b5629ec1340e109565afce4cfb8adb26d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
